# Generated by Django 3.2.5 on 2022-03-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name_project',
            new_name='name',
        ),
    ]
