# Generated by Django 3.2.5 on 2022-03-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220318_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adress',
            field=models.CharField(default=1, max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='brand',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Бренд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contacts',
            field=models.CharField(default=1, max_length=200, verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='engineer',
            field=models.CharField(default=1, max_length=200, verbose_name='Инженер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('FN', 'Закончен'), ('IW', 'В работе')], default='IW', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_number',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Номер контракта'),
        ),
    ]
