# Generated by Django 3.2.5 on 2022-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220328_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Закончен', 'Закончен'), ('В работе', 'В работе')], default='В работе', max_length=20, verbose_name='Статус'),
        ),
    ]
