# Generated by Django 3.2.5 on 2022-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('contract_number', models.IntegerField(db_index=True, unique=True, verbose_name='Номер контракта')),
                ('brand', models.CharField(db_index=True, max_length=200, verbose_name='Бренд')),
                ('contractor', models.CharField(db_index=True, max_length=200, verbose_name='Подрядчик')),
                ('contractor_contract', models.IntegerField(db_index=True, unique=True, verbose_name='Номер договора с подрядчиком')),
                ('advance_payment1', models.CharField(max_length=200, verbose_name='Аванс')),
                ('advance_payment2', models.CharField(max_length=200, verbose_name='Аванс')),
                ('advance_payment3', models.CharField(max_length=200, verbose_name='Аванс')),
                ('final_sum', models.CharField(max_length=200, verbose_name='Итоговая сумма')),
                ('cs_upd', models.CharField(max_length=200, verbose_name='КС/УПД')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=200, verbose_name='Контакты')),
                ('engineer', models.CharField(max_length=200, verbose_name='Инженер')),
                ('status', models.CharField(choices=[('Закончен', 'Закончен'), ('В работе', 'В работе')], default='В работе', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ('name',),
            },
        ),
    ]
