# Generated by Django 3.2.5 on 2022-03-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_object', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Project1',
        ),
    ]
